### ISSUE TITLE
提交工单报错

### ISSUE THREAD

**Issue by woshiyjs123** [youshutong2080/shutongFlow#13]
新建工单，提交报错
None tickets can be created
![image](https://user-images.githubusercontent.com/6252630/57217825-462e0500-7026-11e9-9aff-b66a4c6398b1.png)
![image](https://user-images.githubusercontent.com/6252630/57217851-5645e480-7026-11e9-8809-ae362a04e3e7.png)
![image](https://user-images.githubusercontent.com/6252630/57217889-770e3a00-7026-11e9-9882-cf2a166a4808.png)
![image](https://user-images.githubusercontent.com/6252630/57217904-7d9cb180-7026-11e9-86e1-63b092801fbf.png)
![image](https://user-images.githubusercontent.com/6252630/57217923-88efdd00-7026-11e9-9193-5af4a0f6668d.png)
![image](https://user-images.githubusercontent.com/6252630/57217957-a0c76100-7026-11e9-959b-6079473d6782.png)
![image](https://user-images.githubusercontent.com/6252630/57217969-aae95f80-7026-11e9-8174-d0f6d61c2f01.png)

**Comment by blackholll** [comment]
工作流编辑界面  有个限制条件表达式， 应该是你限制条件表达式配置错了

**Comment by blackholll** [comment]
需要额外知道下count 和level

**Comment by blackholll** [comment]
![image](https://user-images.githubusercontent.com/6269605/57218217-5abecd00-7027-11e9-892b-1ffd2a879ab0.png)

**Comment by woshiyjs123** [comment]
多谢回答，问题已解决
