### ISSUE TITLE
工单驳回富文本框不能初始化和编辑

### ISSUE THREAD

**Issue by woshiyjs123** [youshutong2080/shutongFlow#14]
流程图如下：
![image](https://user-images.githubusercontent.com/6252630/57369748-f172c180-71c0-11e9-8b16-251f31ca49aa.png)
正常填单提交：
![image](https://user-images.githubusercontent.com/6252630/57369832-2b43c800-71c1-11e9-8dae-a4169b241ded.png)
DBA接单后驳回
提交人重新登陆到待办，进入工单详情：
![image](https://user-images.githubusercontent.com/6252630/57369955-87a6e780-71c1-11e9-8fac-96e56bfb8a7d.png)
发现浏览器返回了上线描述数据，但是页面上没有初始化，也不能编辑。
其他非富文本框数据，可以正常显示

**Comment by blackholll** [comment]
最新代码应该已经支持了
