### ISSUE TITLE
不支持附件类型变量

### ISSUE THREAD

**Issue by woshiyjs123** [youshutong2080/shutongFlow#15]
![image](https://user-images.githubusercontent.com/6252630/57452579-c65aa180-7296-11e9-9fe8-ca797ff8160c.png)
![image](https://user-images.githubusercontent.com/6252630/57452632-e9855100-7296-11e9-87d1-8f7be9190dd7.png)
附件类型的变量，填写信息的时候，没有上传按钮

**Comment by blackholll** [comment]
附件的逻辑是这样的：loonflow返回的数据中会有类型，前端自己实现上传附件逻辑到自己的后端，然后提交的时候吧上传后的路径作为值传给loonflow. 目前这个demo暂时还没做这个支持

**Comment by woshiyjs123** [comment]
好的，多谢
