### ISSUE TITLE
npm run dev 时报错html-webpack-plugin

### ISSUE THREAD

**Issue by yangmingbai** [youshutong2080/shutongFlow#16]
npm run dev时报错 提示：
shutongFlow\fronted\node_modules\html-webpack-plugin\li
b\compiler.js:81
        var outputName = compilation.mainTemplate.applyPluginsWaterfall('asset-path', outputOptions.filename, {
TypeError: compilation.mainTemplate.applyPluginsWaterfall is not a function...}

**Comment by yangmingbai** [comment]
版本使用3.2.0时没问题

**Comment by lizeyun** [comment]
> 版本使用3.2.0时没问题

请问你说的3.2.0 是什么版本，nodejs 还是什么呀

**Comment by yangmingbai** [comment]
使用作者提供的packag.json里的安装包版本运行起来没问题

**Comment by lizeyun** [comment]
> 使用作者提供的packag.json里的安装包版本运行起来没问题

没用过nodejs 不是很懂。 我就是用的作者给的命令，npm run dev的时候报错，
![image](https://user-images.githubusercontent.com/19726385/60087133-f8ed2a80-976e-11e9-8111-890a7a4694de.png)
然后，自己手动npm install webpack-cli
再次运行 npm run dev 又报错
npm install webpack-cli
![image](https://user-images.githubusercontent.com/19726385/60087212-26d26f00-976f-11e9-9b43-52f02676eb9c.png)

有没有办法啊，

**Comment by blackholll** [comment]
node使用v8.x以上版本
