### ISSUE TITLE
shutongFlow用户能和 loonflow 中的用户同步么？

### ISSUE THREAD

**Issue by weavepub** [youshutong2080/shutongFlow#19]
shutongFlow 和 loonflow 中的账号不相同，可以用同一套账号管理么？

**Comment by blackholll** [comment]
shutongflow可以配置下ldap，让用户可以直接用ldap账户登录。   loonflow因为管理后台权限校验只限制了登录用户，所以只允许需要配置工作流的用户登录loonflow。 其他用户只要同步用户账户名， 所属部门这些信息就可以了。密码随便设置以下，保障非管理员用户不能登录loonflow

**Comment by weavepub** [comment]
有 shutongFlow 配置 ldap 的说明么？

**Comment by blackholll** [comment]
直接搜索django ldap

**Comment by weavepub** [comment]
shutongflow配置了ldap，loonflow管理端没有配置ldap。工单流程审批人通过ldap账号登入shutongflow，在“我的代办”中没有该工单，在“我相关的”中能查看需要处理的工单。按道理应该“我的代办”和“我相关的”都能看到该待处理的工单吧？是否还得手动同步shutongflow账号到loonflow管理端中？

**Comment by blackholll** [comment]
1.loonflow的用户及部门信息 需要你单独写个定时任务单独操作数据库来同步。 非管理员(不需要配置流程的) 设置随机密码，避免非管理员可以登录loonflow的管理后台
2. 我的待办中没有，检查下调用loonflow的接口是是否在header里面传了正确的用户。

**Comment by weavepub** [comment]
请求里面提示用户不存在，是不是第一件事情就是做用户同步？
