### ISSUE TITLE
关于loonflow r0.3.23和shutongflow的自定义字段无法显示bug

### ISSUE THREAD

**Issue by exampleK** [youshutong2080/shutongFlow#26]
目前解决办法
<img width="660" alt="注释即可" src="https://user-images.githubusercontent.com/22605796/74587380-bf826b80-502c-11ea-9d18-9ed5465c3be3.png">

注释即可，等发现后遗症再说吧

**Comment by blackholll** [comment]
你是吧 def new_ticket  中  if key in update_field_list注释了？
这段的是基于工作流初始状态配置里面的表单字段设置来定的，你希望保持自定义和字段，那么在工作流初始状态吧这个字段设置为可选或者必填，这里就会接受并保存这个字段的值

**Comment by exampleK** [comment]
test
