### ISSUE TITLE
新建工单时弹这个提示，请问什么原因？

### ISSUE THREAD

**Issue by winvip8** [youshutong2080/shutongFlow#27]
![image](https://user-images.githubusercontent.com/10652628/77049462-14861880-6a03-11ea-872b-d25fb87501f1.png)

**Comment by winvip8** [comment]
好了, 原来loonflow的REDIS服务没开起

**Comment by blackholll** [comment]
loonflow实际有返回失败原因的。只是shutongflow没有将msg信息透传过来，而是显示msg:''。导致无法很直观的知道失败原因
