### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by mawennan** [youshutong2080/shutongFlow#3]
你好，我使用的master版本，登陆提示失败

> Bad Request: /api/v1/account/obtain_token/
[19/Oct/2018 10:50:26] "POST /api/v1/account/obtain_token/ HTTP/1.1" 400 68

**Comment by blackholll** [comment]
hi，只有这个信息不好排查。 sql导入了么？ 你如果是本地环境的话，可以加个断点调试下：
apps/account/views.py   line19

class ShutongObtainJSONWebToken(ObtainJSONWebToken):
    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            userObj = serializer.object.get('user') or request.user
            userObj.last_login = timezone.datetime.now()
            userObj.save()
        return super(ShutongObtainJSONWebToken, self).post(request, *args, **kwargs)

**Comment by mawennan** [comment]
非常感谢你的回复，sql我都导入了，这是我断点print出来的信息

> {'username': 'admin', 'password': 'yxuqtr'}
JSONWebTokenSerializer(context={'request': <rest_framework.request.Request object>, 'view': <account.views.ShutongObtainJSONWebToken object>}, data={'username': 'admin', 'password': 'yxuqtr'}):
    username = CharField()
    password = PasswordField(write_only=True)
Bad Request: /api/v1/account/obtain_token/
[19/Oct/2018 11:18:26] "POST /api/v1/account/obtain_token/ HTTP/1.1" 400 68

**Comment by blackholll** [comment]
我重新初始化了一个，没问题。  
你是python3版本么。需要python3的

**Comment by mawennan** [comment]
我重新初始化还是有问题，python用的3.7 可能太高了吧， 我试试3低版本的。谢谢啦。

**Comment by mawennan** [comment]
.. 因为我没有创建createsuperuser，所以登陆失败了。

**Comment by blackholll** [comment]
shutongflow.sql里面有导入admin用户。不需要createsuperuser的啊
