### ISSUE TITLE
查询不到我创建的工单

### ISSUE THREAD

**Issue by Vnimos** [youshutong2080/shutongFlow#34]
新建工单，且提示创建成功了，但在我创建的菜单里，查询不到已创建的工单

**Comment by blackholll** [comment]
可能是创建失败了， shutongflow提示有问题,  看下loonflow的日志，

**Comment by Vnimos** [comment]
实际上是创建成功了，只是前端的用户管理和loonflow的用户是分离的，所以看不到，在loonflow上创建相应的用户就行了
issues上有提到可以接ldap，这个是需要改代码吗

**Comment by blackholll** [comment]
shutongflow可以接ldap，qq群文件中（558788490）有配置说明可以参考下。
loonflow因为涉及到部门、部门审批人，这些信息很多公司ldap中都没有，所以没做支持

**Comment by wangxuanwx** [comment]
你好，我也遇到这样的问题，在loonflow上创建了相应的用户也没起作用，请问是什么原因

**Comment by blackholll** [comment]
先看下loonflow的日志， 默认是启动用户的家目录下 loonflow.log
