### ISSUE TITLE
数据显示问题

### ISSUE THREAD

**Issue by wangxuanwx** [youshutong2080/shutongFlow#37]
你好，我创建了很多工单，在浏览工单时，页码对应显示的数据有问题，请问在哪修改

**Comment by blackholll** [comment]
具体什么问题? 截图看下

**Comment by wangxuanwx** [comment]
![屏幕截图 2020-11-23 180132](https://user-images.githubusercontent.com/72643275/99949577-3ae02d00-2db6-11eb-91b2-0de592310e61.png)
这是第二页
![屏幕截图 2020-11-23 180210](https://user-images.githubusercontent.com/72643275/99949603-459ac200-2db6-11eb-8d3e-82c936a1b76a.png)
这是第三页
就是最后几个会和前面的重复

**Comment by blackholll** [comment]
shutongflow的前端么？
下面几个文件  分别对应  我创建的、我的待办等列表
https://github.com/youshutong2080/shutongFlow/tree/master/fronted/src/components/ticket

**Comment by wangxuanwx** [comment]
是shutongflow,我在这里面改了每页显示的内容个数，好像到一定数量，数据的排列就会变

**Comment by blackholll** [comment]
嗯 shutongflow是个demo， 需要自己修改下
