### ISSUE TITLE
shutongflow前端删除功能

### ISSUE THREAD

**Issue by wangxuanwx** [youshutong2080/shutongFlow#38]
![屏幕截图 2020-11-26 114601](https://user-images.githubusercontent.com/72643275/100305950-32b60680-2fdd-11eb-9159-16572f2de4de.png)
想请教shutongflow前端的删除命令如何实现

**Comment by blackholll** [comment]
这是删除什么内容， 工作流？ 还是工单？
工单目前未提供删除功能
工作流的话  loonflow管理后台可以操作删除
