### ISSUE TITLE
创建工单显示成功了，但是没有任何记录

### ISSUE THREAD

**Issue by gengkeye** [youshutong2080/shutongFlow#66]
如题，创建工单显示成功了，返回的状态码是200，但是使用管理员权限也看不到任何工单创建的记录，排除是权限问题造成的，查看loonflow数据库ticket_ticketrecord表和其它ticket相关的表也没有看到任何数据。

**Comment by blackholll** [comment]
查看下loonflow的日志。估计是实际创建失败了 但是shutongflow未正确判断

**Comment by gengkeye** [comment]
感谢你的回复，问题已经解决。原因是Redis的配置错误了，导致无法连接Redis。
修正redis配置后，正常了。
