### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by YuZongYangHi** [youshutong2080/shutongFlow#8]
mysql> grant all privileges on shutongflow.* to shutongflow@127.0.0.1 identified by '123456';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'identified by '123456'' at line 1

**Comment by blackholll** [comment]
应该是你复制命令 然后粘贴的时候 引号没转成中文引号了，检查下
